// <auto-generated />
using InvennaOpdracht.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvennaOpdracht.Server.Migrations
{
    [DbContext(typeof(InvennaDbContext))]
    [Migration("20250617171928_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvennaOpdracht.Server.Data.Models.GeographicalDataItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gemeente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HuisLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HuisNummerToevoeging")
                        .HasColumnType("int");

                    b.Property<int>("Huisnummer")
                        .HasColumnType("int");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("NevenAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NummerAanduiding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Object_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Object_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenbareRuimte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OppervlakteVerblijfsobject")
                        .HasColumnType("int");

                    b.Property<int>("PandBouwjaar")
                        .HasColumnType("int");

                    b.Property<string>("PandId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PandStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerblijfsobjectGebruiksdoel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerblijfsobjectStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Woonplaats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GeographicalDataItems");
                });
#pragma warning restore 612, 618
        }
    }
}
